# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

after_failure:
  - cat $TRAVIS_BUILD_DIR/stests.Rcheck/00install.out
  - cat $TRAVIS_BUILD_DIR/stests.Rcheck/00check.log
